[ERROR] 2020-04-08 16:06:59,061 | /home/ntah/frappe-bench/apps/frappe/frappe/app.py:
Site: meeting.dev
Form Dict: {
 "action": "Save",
 "cmd": "frappe.desk.form.save.savedocs",
 "doc": "{\"owner\":\"Administrator\",\"title\":\"ERPNext Discussion\",\"attendees\":[{\"owner\":\"Administrator\",\"accepted\":0,\"idx\":1,\"doctype\":\"Meeting Attendee\",\"docstatus\":0,\"name\":\"a259d24f74\",\"attended\":0,\"parentfield\":\"attendees\",\"parent\":\"Meeting-1\",\"modified\":\"2020-04-08 15:09:06.439731\",\"creation\":\"2020-04-07 17:46:06.115049\",\"parenttype\":\"Meeting\",\"modified_by\":\"Administrator\",\"attendee\":\"ntahlah@admin.com\"}],\"idx\":0,\"to_time\":\"17:45:55\",\"docstatus\":0,\"doctype\":\"Meeting\",\"date\":\"2020-04-07\",\"status\":\"Planned\",\"agenda\":[{\"owner\":\"Administrator\",\"idx\":1,\"doctype\":\"Meeting Agenda\",\"docstatus\":0,\"parentfield\":\"agenda\",\"parent\":\"Meeting-1\",\"description\":\"To discuss about ERPNext\",\"modified\":\"2020-04-08 15:09:06.439731\",\"creation\":\"2020-04-07 17:46:06.115049\",\"parenttype\":\"Meeting\",\"modified_by\":\"Administrator\",\"name\":\"96fe3f0fdc\"}],\"from_time\":\"17:45:55\",\"minutes_meeting\":[],\"modified\":\"2020-04-08 15:09:06.439731\",\"creation\":\"2020-04-07 17:46:06.115049\",\"modified_by\":\"Administrator\",\"name\":\"Meeting-1\",\"__last_sync_on\":\"2020-04-08T07:18:18.885Z\",\"__unsaved\":1}"
}
Request Error
Traceback (most recent call last):
  File "/home/ntah/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/ntah/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/ntah/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/ntah/frappe-bench/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/ntah/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/ntah/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/ntah/frappe-bench/apps/frappe/frappe/model/document.py", line 296, in _save
    self.run_before_save_methods()
  File "/home/ntah/frappe-bench/apps/frappe/frappe/model/document.py", line 876, in run_before_save_methods
    self.run_method("validate")
  File "/home/ntah/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ntah/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ntah/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ntah/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/ntah/frappe-bench/apps/meeting/meeting/meeting/doctype/meeting/meeting.py", line 16, in validate
    attendee.full_name = " ".join(filter(None, [user, first_name, user.middle_name, user.last_name]))
NameError: name 'first_name' is not defined
